= openfortivpn Container
Jordan Williams <jordan@jwillikers.com>
:experimental:
:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:Podman: https://podman.io/[Podman]
:Buildah: https://buildah.io/[Buildah]
:Fedora: https://getfedora.org/[Fedora]
:openfortivpn: https://github.com/adrienverge/openfortivpn[openfortivpn]

// todo image:https://img.shields.io/github/workflow/status/jwillikers/openfortivpn-container[GitHub Workflow Status]

A container image for the running the {openfortivpn} client.

== Quick Start

To run openfortivpn from this image, run the container using Podman.

[source,sh]
----
➜ sudo podman run --rm -it \
                    --net host \
                    --device /dev/ppp \
                    --privileged \
                    localhost/openfortivpn sudo openfortivpn
----

== Build

Use Buildah to build the image.
The script is written for the fish shell.

. Install the necessary dependencies.
+
[source,sh]
----
➜ sudo dnf -y install fish git buildah podman
----

. Clone this repository.
+
[source,sh]
----
➜ git -C ~/Projects clone git@github.com:jwillikers/openfortivpn-container.git
----

. Run the shell script.
+
[source,sh]
----
➜ sudo fish ~/Projects/openfortivpn.fish
----

== Contributing

Contributions in the form of issues, feedback, and even pull requests are welcome.
Make sure to adhere to the project's link:CODE_OF_CONDUCT.adoc[Code of Conduct].

== Open Source Software

This project is built on the hard work of countless open source contributors.
Several of these projects are enumerated below.

* https://www.ansible.com/[Ansible]
* https://asciidoctor.org/[Asciidoctor]
* {Fedora}
* https://git-scm.com/[Git]
* https://www.linuxfoundation.org/[Linux]
* https://molecule.readthedocs.io/en/latest/[Molecule]
* https://www.openssh.com/[OpenSSH]
* https://podman.io/[Podman]
* https://www.python.org/[Python]
* https://rouge.jneen.net/[Rouge]
* https://www.ruby-lang.org/en/[Ruby]

== Code of Conduct

The project's Code of Conduct is available in the link:CODE_OF_CONDUCT.adoc[Code of Conduct] file.

== License

This repository is licensed under the https://www.gnu.org/licenses/gpl-3.0.html[GPLv3], available in the link:LICENSE.adoc[license file].

© 2021 Jordan Williams

== Authors

mailto:{email}[{author}]
