= openfortivpn Container
Jordan Williams <jordan@jwillikers.com>
:experimental:
:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:Asciidoctor_: https://asciidoctor.org/[Asciidoctor]
:Buildah: https://buildah.io/[Buildah]
:Fedora: https://getfedora.org/[Fedora]
:Fedora-Silverblue: https://silverblue.fedoraproject.org/[Fedora Silverblue]
:fish: https://fishshell.com/[fish]
:Git: https://git-scm.com/[Git]
:Linux: https://www.linuxfoundation.org/[Linux]
:openfortivpn: https://github.com/adrienverge/openfortivpn[openfortivpn]
:Podman: https://podman.io/[Podman]
:pre-commit: https://pre-commit.com/[pre-commit]
:Python: https://www.python.org/[Python]
:Rouge: https://rouge.jneen.net/[Rouge]
:Ruby: https://www.ruby-lang.org/en/[Ruby]

image:https://img.shields.io/github/workflow/status/jwillikers/openfortivpn-container/CI/main[GitHub Workflow Status]
image:https://img.shields.io/badge/pre--commit-enabled-brightgreen?logo=pre-commit&logoColor=white[pre-commit, link=https://github.com/pre-commit/pre-commit]

A container image for the running the {openfortivpn} client.

== Synopsis

This container is meant to be used to connect to a Fortinet VPN.
You might find this workflow particularly helpful if you develop on an immutable base operating system, such as {Fedora Silverblue}.

Image:: https://quay.io/repository/jwillikers/openfortivpn[quay.io/jwillikers/openfortivpn]

Tags::
* `latest`

Supported architectures::
* `amd64` _(x86_64)_
* `arm64` _(aarch64)_

Labels::
`io.containers.autoupdate=registry`::: Enables automatic updates when using {Podman} and the _fully-qualified_ image name.

== Quick Start

To run openfortivpn from this image, run the container as root using Podman filling in necessary information to the openfortivpn command-line to connect to the VPN for your specific use-case.

[source,sh]
----
sudo podman run -it \
  --device /dev/ppp \
  --net host \
  --privileged \
  --rm \
  quay.io/jwillikers/openfortivpn:latest \
  sudo openfortivpn vpn.<company-domain>.com:443 \
  --username=<active-directory-domain>\\<username> \
  --trusted-cert <trusted-cert>
----

== Build

Use Buildah to build the image.
The script is written for the fish shell.

. Install the necessary dependencies.
+
[source,sh]
----
sudo dnf -y install fish git buildah podman
----

. Clone this repository.
+
[source,sh]
----
git -C ~/Projects clone git@github.com:jwillikers/openfortivpn-container.git
----

. Install {pre-commit}.
+
[source,sh]
----
pip install pre-commit
----

. Change into the project directory.
+
[source,sh]
----
cd ~/Projects/openfortivpn-container
----

. Install pre-commit's Git hooks.
+
[source,sh]
----
pre-commit install
----

. Run the shell script.
+
[source,sh]
----
sudo fish ~/Projects/openfortivpn-container/build.fish
----

== Contributing

Contributions in the form of issues, feedback, and even pull requests are welcome.
Make sure to adhere to the project's link:CODE_OF_CONDUCT.adoc[Code of Conduct].

== Open Source Software

This project is built on the hard work of countless open source contributors.
Several of these projects are enumerated below.

* {Asciidoctor_}
* {Buildah}
* {Fedora}
* {Fedora-Silverblue}
* {fish}
* {Git}
* {Linux}
* {openfortivpn}
* {Podman}
* {pre-commit}
* {Python}
* {Rouge}
* {Ruby}

== Code of Conduct

Refer to the project's link:CODE_OF_CONDUCT.adoc[Code of Conduct] for details.

== License

This repository is licensed under the https://www.gnu.org/licenses/gpl-3.0.html[GPLv3], a copy of which is provided in the link:LICENSE.adoc[license file].

© 2021 Jordan Williams

== Authors

mailto:{email}[{author}]
